
# Permalinks
# permalink: pretty
permalink: /:title/

# Setup
baseurl: /learning-diary
title: Luentop채iv채kirja
tagline: Ohjelmistoturvallisuus-kurssin luentop채iv채kirja.
exclude: ['README.md']
include: ['_pages']